### PR TITLE
Fix lint

### LINKED ISSUE #5: MNT: The autoconf recipe has some lint :(
This is the friendly conda-forge-admin automated user.

I've ran the conda-smithy linter and found some lint in this feedstock :cry:.

Here is what I have got:

  * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).

Thanks!

### PR DESCRIPTION
**Pull request by ocefpaf**
Fixes #5

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please use `conda-smithy` 0.9.2 to re-render?

**Comment by ocefpaf** [comment]
> Could you please use `conda-smithy` 0.9.2 to re-render?

I am. What change are you missing?

**Comment by ocefpaf** [comment]
Oh I see. I was with a `dev` version without the brew cleaning. But that is not important here. (In fact I am not sure we have a case where that will be important.).

**Comment by jakirkham** [comment]
Oh, maybe there was a change after the diff I looked at. It now looks fine.

**Comment by jakirkham** [comment]
Some of the more memory intensive builds worry me a bit as they could hang. Like FFTW I have had to restart sometimes.

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Pull request merged**
