### PR TITLE
Add perl as a run dep

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @kmuehlbauer this might help fix our problems.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Seems it needs perl also at build time...

**Comment by ocefpaf** [comment]
> Seems it needs perl also at build time...

I did that to investigate if `autoconf` was the right place for the `perl` dependency here, but I guess `m4` is. (At least my Linux distro builds `m4` with `perl`.)

**Comment by ocefpaf** [comment]
I don't know what is causing the `perl` conflict. It is definitely not `m4` which is the only dependency for `autoconf`.

```shell
Error:  Package missing in current linux-64 channels: 
  - perl 5.18.2*
```

@msarahan do you have any idea of what I am doing wrong here?

**Comment by msarahan** [comment]
Yeah, conda's dumb in this case.  The default Perl version is the one you see, but that's not available.  Pin to >=5.20 and it should work.

**Comment by ocefpaf** [comment]
Thanks @msarahan! That solved it!! We need to figure out a pinning strategy for `perl` and add it [here](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L31-L49).

Does `perl 5.20.*` sounds OK? If so I can put a PR to add that to the `pin_the_slow_way.py` script. (Ping @pelson.)

**Comment by jakirkham** [comment]
I thought we fixed this `perl` issue. @pelson, any idea why it still doesn't respect the version in the feedstock?

**Comment by pelson** [comment]
> I thought we fixed this perl issue. @pelson, any idea why it still doesn't respect the version in the feedstock?

Good question. I definitely added conda-build-all perl support (https://github.com/SciTools/conda-build-all/blob/master/conda_build_all/version_matrix.py#L217) so yes, the CONDA_PERL environment variable should be being set appropriately (and automatically).

**Comment by jakirkham** [comment]
Ah, but we didn't add it to `conda-smithy`.

**Comment by jakirkham** [comment]
FYI this is not the last time `perl` issues will come out of the woodwork. I expect to see several in the near future. We were implicitly depending on `perl` that was installed with `git` from `yum`. However, we now use our `git` that does not install `perl` currently (may change). As a result, a few packages may need to be fixed to have `perl` as a build and/or run time dependency.

**Comment by jakirkham** [comment]
FYI `automake` had the same issue, but it is now fixed.

**Pull request merged**
