### PR TITLE
No Win

### PR DESCRIPTION
**Pull request by ocefpaf**
Don't need to build on Windows.

### CODE REVIEW

**Comment by jakirkham** [comment]
Weird that AppVeyor queues anyways.

**Comment by ocefpaf** [comment]
I guess we need to unhook it in the AppVeyor config.

**Comment by ocefpaf** [comment]
Maybe we need to check this in every project... Not cool.

appv

**Comment by jakirkham** [comment]
What about something like this? We could make the message and author `.*` or however they are doing regex?

```
# Skipping commits with particular message or from user
skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message
  author: John        # Commit author's username, name, email or regexp maching one of these.
```

cc @pelson

**Comment by ocefpaf** [comment]
If I got that correct it is the same as commit with `[skip appveyor]`, no?

**Comment by jakirkham** [comment]
Maybe not exactly because it might have to clone first, but it will at least be a fast finish.

**Comment by jakirkham** [comment]
I tried my hand at it to see how this would go ( https://github.com/conda-forge/autoconf-feedstock/pull/3 ). We probably should get it into conda-smithy instead of leaving it here though.

**Comment by jakirkham** [comment]
Another thought is, might there be a global setting for skipping builds without `appveyor.yml`?

**Comment by pelson** [comment]
Try enabling the skip without appveyor item.
I will try to roll that out across all feedstocks in the next day or so.

**Comment by jakirkham** [comment]
There is a [`GET`]( https://www.appveyor.com/docs/api/projects-builds#get-project-settings )/[`PUT`]( https://www.appveyor.com/docs/api/projects-builds#update-project ) API that can be used here. Basically, get the project settings then set `skipBranchesWithoutAppveyorYml` to `true` and `PUT` the modified json.

**Comment by pelson** [comment]
> There is a GET/PUT API that can be used here. Basically, get the project settings then set skipBranchesWithoutAppveyorYml to true and PUT the modified json.

It was my plan to use this, but I seem to have failed miserably to just their config api. I'm forever getting a 400, even when repeating the same response I tracked in Chrome developer tools. Have you tried this yourself @jakirkham?

**Comment by jakirkham** [comment]
I have not. Did you write something I could look at somewhere? Maybe we can do a little pair coding session. :wink:

**Comment by pelson** [comment]
From the scope of https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/ci_register.py:

```
def appveyor_configure(user, project):
    import ruamel.yaml

    headers = {'Authorization': 'Bearer {}'.format(appveyor_token)}
    url = 'https://ci.appveyor.com/api/projects/{}/{}/settings'.format(user, project)
    print(url)
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        raise ValueError(response)
    foo = response.content
    f = response.content
    project = response.json()['project']
    print(project)
    project['skipBranchesWithoutAppveyorYml'] = True
    print(project)

    url = 'https://ci.appveyor.com/api/projects'.format(user, project)
    headers['Content-Type'] = 'application/json'
    headers.update({
               'User-Agent': 'Mozilla/5.0',
               'Accept': 'application/json, text/plain, */*',
               'Content-Type': 'application/json;charset=UTF-8',
               'Origin': 'https://ci.appveyor.com',
               })

    response = requests.put(url, headers=headers, json=project)
    if response.status_code != 200:
        print(response.text)
        raise ValueError(response)
```


Called with:

```
    appveyor_configure('conda-forge', 'm4-feedstock')
    appveyor_configure('conda-forge', 'lmdb-feedstock')
```

**Comment by ocefpaf** [comment]
This PR is no longer needed.

**Comment by pelson** [comment]
For the record, this got solved by https://github.com/conda-forge/conda-smithy/pull/95/files

**Pull request closed without merging**
