### PR TITLE
Rewrite shebang lines in scripts so conda can understand them

### PR DESCRIPTION
**Pull request by jjhelmus**
Rewrite the shebang lines in the autoconf scripts without spaces or ending flags so that conda can properly modify them when creating an environment.

Required to work around conda/conda#3999

### CODE REVIEW

**Comment by jjhelmus** [comment]
Trying to build this with `conda-build` 2.0.x is going to be even more challenging.  The shebang line for tools created in the build and used later in the build are longer than those allowed by most systems (127 characters).  Luckily the package does not contain binary prefixes so there is no need to rebuild this with `conda-build` 2.0.x.

**Comment by ocefpaf** [comment]
OS X is not happy with that change:

```
+ sed -i '1s~.*~#!/Users/travis/miniconda3/envs/_build_placehold_placehold_placehold_placehold_pla/bin/perl~' /Users/travis/miniconda3/envs/_build_placehold_placehold_placehold_placehold_pla/bin/autoheader
sed: 1: "/Users/travis/miniconda ...": undefined label 'ravis/miniconda3/envs/_build_placehold_placehold_placehold_placehold_pla/bin/autoheader'
Command failed: /bin/bash -x -e /Users/travis/miniconda3/conda-bld/work/autoconf-2.69/conda_build.sh
```

**Comment by jjhelmus** [comment]
Apparently GNU sed and BSD sed have different syntax for doing in-place substitution.  I'm not sure if this is the best solution anyway.  Let me think on this a bit and see if there is a better way.  If conda/conda#3999 gets fixed this might not be needed anyways.

Additionally I've found a better solution to the original reason why I went down this path, so it is no longer a priority for me.

**Comment by jakirkham** [comment]
Someone added GNU `sed` awhile back. Would recommend just adding `sed` as a `build` dependency instead of messing around with the syntax.

**Comment by ocefpaf** [comment]
@jjhelmus what is the status of this? Should we close it?

**Comment by jjhelmus** [comment]
I don't believe this is needed anymore.  closing.

**Comment by DamianAgius** [comment]
> Trying to build this with `conda-build` 2.0.x is going to be even more challenging. The shebang line for tools created in the build and used later in the build are longer than those allowed by most systems (127 characters). Luckily the package does not contain binary prefixes so there is no need to rebuild this with `conda-build` 2.0.x.

We have a requirement to build packages (including autoconf) in an air-gapped environment using `conda-build 3.18.11` and are getting the `bad interpreter` errors due to length of shebang during the build (as you would know the `autoconf` build uses `sed` to substitute in `$PREFIX` before running scripts as part of the build).   
As of yet I have not worked out a solution - any ideas?

**Pull request closed without merging**
